# Generated by Django 5.0.6 on 2024-07-10 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_books_bookav'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookav',
            new_name='Book',
        ),
    ]
